name: Build Notion Content

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # 1時間に1回

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Fetch Notion Data
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          WORKS_DB: ${{ secrets.WORKS_DB }}
        run: node scripts/notion.js

      - name: Commit data
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff --cached --quiet || git commit -m "Auto update from Notion"
          git push
